nginx image

diff --git a/docker-compose.dev.yml b/docker-compose.dev.yml
--- a/docker-compose.dev.yml
+++ b/docker-compose.dev.yml
@@ -1,11 +1,36 @@
 services:
+  nginx:
+    build:
+      context: ./nginx
+      dockerfile: dockerfile
+    image: kalebrs/deploysearch-nginx:latest
+    ports:
+      - "80:80"
+    networks:
+      - app-network
+    healthcheck:
+      test: |
+        CMD-SHELL
+        echo "Testing Frontend connection..." &&
+        curl -f http://frontend:8501/_stcore/health &&
+        echo "Testing Backend connection..." &&
+        curl -f http://backend:8051/health ||
+        exit 1
+      interval: 10s
+      timeout: 5s
+      retries: 3
+      start_period: 30s
+    depends_on:
+      frontend:
+        condition: service_healthy
+      backend:
+        condition: service_healthy
+
   frontend:
     build:
       context: ./frontend
       dockerfile: dockerfile
     image: kalebrs/deploysearch-frontend:latest
-    ports:
-      - "8501:8501"
     env_file: .env.dev
     environment:
       - ENV=dev
@@ -16,18 +41,19 @@ services:
     networks:
       - app-network
     healthcheck:
-      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
+      test: ["CMD-SHELL", "curl -v http://localhost:8501/_stcore/health || echo 'Health check failed' >&2"]
       interval: 10s
       timeout: 5s
       retries: 5
+      start_period: 30s
+    ports:
+      - "8501:8501"
 
   backend:
     build:
       context: ./backend
       dockerfile: dockerfile
     image: kalebrs/deploysearch-backend:latest
-    ports:
-      - "8051:8051"
     env_file: .env.dev
     environment:
       - ENV=dev
@@ -44,6 +70,8 @@ services:
       start_period: 60s
     networks:
       - app-network
+    ports:
+      - "8051:8051"
 
   minio:
     build:
